apiVersion: v1
description: The Cloud-Native Ingress and API-management
engine: gotpl
maintainers:
- name: hbagdi
  email: harry@konghq.com
- name: rainest
  email: traines@konghq.com
name: kong
sources:
version: 1.11.0
appVersion: 2.1
